name: Alex Gervais
favicon: null
layout_spectrum: 0.7542920031119138
typography_spectrum: 0.35409240634180605
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3178133354522288
  lightness: 0.4419345890637487
  saturation: 0.38502819323912263
  rhythmicContrast: 0.68549779150635
purpose: []
